import { Piece } from "@/domain/composeDiagram/model/Piece";
import { PieceClasses } from "@/domain/composeDiagram/value/PieceClasses";

export const PieceSetAsDefault: Piece[] = [
  // first Player
  new Piece(PieceClasses.King),
  new Piece(PieceClasses.Gold),
  new Piece(PieceClasses.Gold),
  new Piece(PieceClasses.Silver),
  new Piece(PieceClasses.Silver),
  new Piece(PieceClasses.kNight),
  new Piece(PieceClasses.kNight),
  new Piece(PieceClasses.Lance),
  new Piece(PieceClasses.Lance),
  new Piece(PieceClasses.Bishop),
  new Piece(PieceClasses.Rook),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  // second Player
  new Piece(PieceClasses.King),
  new Piece(PieceClasses.Gold),
  new Piece(PieceClasses.Gold),
  new Piece(PieceClasses.Silver),
  new Piece(PieceClasses.Silver),
  new Piece(PieceClasses.kNight),
  new Piece(PieceClasses.kNight),
  new Piece(PieceClasses.Lance),
  new Piece(PieceClasses.Lance),
  new Piece(PieceClasses.Bishop),
  new Piece(PieceClasses.Rook),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
  new Piece(PieceClasses.Pawn),
];
